listeners:
  - acceptor:
      type: tcp
      bind: 0.0.0.0:3000
  - acceptor:
      type: tcp
      bind: 127.0.0.1:3080
consumers:
  - name: sunli
    auth:
      type: basic
      username: demo
      password: 123456
routes:
  - path: /
    strip: true
    service:
      endpoint:
        type: upstream
        lb: roundrobin
        scheme: http
        nodes:
          - localhost:8000
        websocket: true
    plugins:
      - type: responseRewrite
        headers:
          X-Server: Test Server ({{ remoteAddr }})
globalPlugins:
  - type: prometheus
