listeners:
  - acceptor:
      type: tcp
      bind: 0.0.0.0:8000
  - acceptor:
      type: tcp
      bind: 127.0.0.1:8080
consumers:
  - name: sunli
    auth:
      type: basic
      username: demo
      password: 123456
routes:
  - path: /
    strip: true
    service:
      endpoint:
        type: upstream
        scheme: http
        host: localhost:3000
    plugins:
      - type: responseRewrite
        headers:
          X-Server: Test Server ({{ remoteAddr }})
globalPlugins:
  - type: prometheus